// Generated by CoffeeScript 1.3.3
(function() {
  var $, Plugin,
    __slice = [].slice;

  $ = jQuery;

  Plugin = (function() {

    function Plugin(elem, options) {
      if (options == null) {
        options = {};
      }
      this.elem = elem;
      this.$elem = $(elem);
      this.options = options;
    }

    Plugin.prototype.defaults = {
      title: "Mixtape",
      imagesFolder: "public/images/juke/",
      soundmanagerFolder: "public/swf/",
      placeholder: "images/juke/default.jpg",
      trackinfo: "trackinfo.json",
      SM2: "public/docs/js/min/soundmanager2.min.js",
      itunes: true,
      audio: "mix.mp3",
      tooltips: false,
      animationSpeed: 400,
      debug: false
    };

    Plugin.prototype.load = function() {
      var _this = this;
      $.ajaxSetup({
        xhr: function() {
          if (window.ActiveXObject) {
            return new ActiveXObject("Microsoft.XMLHTTP");
          } else {
            return new XMLHttpRequest();
          }
        }
      });
      this.settings = $.extend({}, this.defaults, this.options);
      window.SM2_DEFER = true;
      return $.ajax({
        url: this.settings.SM2,
        success: function() {
          window.soundManager = new SoundManager();
          soundManager.url = _this.settings.soundmanagerFolder + 'soundmanager2_flash_xdomain/';
          soundManager.useHTML5Audio = true;
          soundManager.autoLoad = true;
          soundManager.preferFlash = false;
          soundManager.consoleOnly = true;
          soundManager.debugMode = _this.settings.debug;
          soundManager.wmode = 'transparent';
          soundManager.beginDelayedInit();
          return _this.init();
        }
      });
    };

    Plugin.prototype.init = function() {
      var extension,
        _this = this;
      this.currentTrack = 1;
      this.cur = 0;
      this.title = document.title;
      this.$elem.css({
        "display": "block",
        "visibility": "hidden"
      });
      if (this.isJSON(this.settings.trackinfo)) {
        this.parseTrackInfo($.parseJSON(this.settings.trackinfo));
      } else {
        $.ajax({
          url: this.settings.trackinfo,
          async: false,
          success: function(data) {
            return _this.parseTrackInfo(data);
          }
        });
      }
      extension = window.devicePixelRatio > 1 ? '@2x.png' : '.png';
      this.$elem.children().wrapAll('<ul id="tapebox"/>');
      this.tapebox = $("#tapebox");
      this.tapebox.wrapAll('<div id="displaybox"/>');
      this.tapebox.prepend("<li><img src='" + this.settings.placeholder + "' width='125'></li>");
      $("#displaybox").prepend("<img src='" + this.settings.imagesFolder + "bg" + extension + "'>");
      this.$elem.prepend("<div id='shadowleft' class='shadow'></div>\n<div id='shadowright' class='shadow'></div>\n<div id='playhead'>\n  <img src='" + this.settings.imagesFolder + "playhead_overlay" + extension + "'>\n  <div id='playtoggle' class='hover'></div>\n</div>");
      this.$elem.append("<div id='displaybox_overlay'>\n  <img src='" + this.settings.imagesFolder + "displaybox_overlay" + extension + "' />\n</div>");
      if (this.settings.tooltips) {
        this.$elem.append("<div class='tooltip'>" + this.settings.title + "</div>");
        this.tooltip = $(".tooltip");
      }
      this.shadowleft = $("#shadowleft");
      this.shadowright = $("#shadowright");
      this.playtoggle = $("#playtoggle");
      soundManager.onready(function() {
        soundManager.createSound({
          id: "juke",
          url: $.trim(_this.settings.audio),
          onplay: function() {
            _this.playtoggle.addClass('playing');
            document.title = "\u25B6 " + _this.settings.title + " - " + _this.title;
            if (_this.cur === 0) {
              _this.tapeOffset = _this.tapebox.parent().width() / 2 - 63 - 125;
              _this.tapebox.animate({
                "left": _this.tapeOffset
              }, _this.settings.animationSpeed, "swing");
              if (_this.settings.tooltips) {
                return _this.updateInfo(_this.trackInfo[_this.currentTrack - 1].artist, _this.trackInfo[_this.currentTrack - 1].track);
              }
            }
          },
          onpause: function() {
            _this.playtoggle.removeClass('playing');
            return document.title = _this.title;
          },
          onfinish: function() {
            _this.playtoggle.removeClass('playing');
            return document.title = _this.title;
          },
          whileplaying: function() {
            _this.cur = parseInt(soundManager.getSoundById("juke").position / 1000, 10);
            if (_this.cur >= _this.duration) {
              soundManager.pause("juke");
            }
            if (_this.cur >= _this.nextMarker) {
              _this.currentTrack += 1;
              if (_this.currentTrack < _this.numTracks) {
                _this.currentMarker = _this.nextMarker;
                _this.nextMarker = _this.getMarker(_this.currentTrack);
              } else {
                _this.nextMarker = _this.duration;
              }
              _this.tapebox.animate({
                "left": "-=125px"
              }, _this.settings.animationSpeed, "swing");
              if (_this.settings.tooltips) {
                _this.updateInfo(_this.trackInfo[_this.currentTrack - 1].artist, _this.trackInfo[_this.currentTrack - 1].track);
              }
            }
            return _this.log("total: " + _this.duration + ", currently at: " + _this.cur + ", next marker: " + _this.nextMarker);
          }
        });
        _this.playtoggle.on('mousedown', function() {
          return soundManager.togglePause("juke");
        });
        if (_this.settings.debug) {
          _this.$elem.append('<span id="skipbackward">REV</span>&nbsp;-&nbsp;<span id="skipforward">FWD</span>');
          $("#skipforward").click(function() {
            return soundManager.getSoundById("juke").setPosition(soundManager.getSoundById("juke").position + 5000);
          });
          $("#skipbackward").click(function() {
            return soundManager.getSoundById("juke").setPosition(soundManager.getSoundById("juke").position - 5000);
          });
        }
        _this.adjustDimensions();
        _this.$elem.css("visibility", "visible");
        return $(window).resize(function() {
          return _this.adjustDimensions();
        });
      });
      return this;
    };

    Plugin.prototype.log = function() {
      var msg;
      msg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (this.settings.debug) {
        return typeof console !== "undefined" && console !== null ? console.log(msg) : void 0;
      }
    };

    Plugin.prototype.isJSON = function(str) {
      if (!str.length) {
        false;
      }
      str = str.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g, '@');
      str = str.replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g, ']');
      str = str.replace(/(?:^|:|,)(?:\s*\[)+/g, '');
      return /^[\],:{}\s]*$/.test(str);
    };

    Plugin.prototype.parseTrackInfo = function(data) {
      this.trackInfo = data;
      this.log(this.trackInfo);
      this.duration = this.parseTime(this.trackInfo.duration);
      this.trackInfo = this.trackInfo.tracks;
      this.currentMarker = this.getMarker(this.currentTrack - 1);
      this.nextMarker = this.getMarker(this.currentTrack);
      return this.numTracks = parseInt(this.trackInfo.length, 10);
    };

    Plugin.prototype.adjustDimensions = function() {
      var tapeOffset;
      this.shadowleft.css({
        right: this.shadowleft.parent().width() / 2 + 63
      });
      this.shadowright.css({
        left: this.shadowright.parent().width() / 2 + 64
      });
      tapeOffset = this.tapebox.parent().width() / 2 - 62;
      if (this.cur > 0) {
        tapeOffset -= this.currentTrack * 125;
      }
      return this.tapebox.css({
        left: tapeOffset
      });
    };

    Plugin.prototype.parseTime = function(time) {
      var min, minutePattern, sec, secondPattern, testPattern;
      testPattern = /:/;
      minutePattern = /^\d*(?=:)/;
      secondPattern = /[0-5][0-9]$/;
      if (testPattern.test(time)) {
        min = parseInt(minutePattern.exec(time), 10);
        sec = parseInt(secondPattern.exec(time), 10);
        return min * 60 + sec;
      } else {
        return parseInt(time, 10);
      }
    };

    Plugin.prototype.getMarker = function(index) {
      var marker;
      marker = this.trackInfo[index].marker;
      return this.parseTime(marker);
    };

    Plugin.prototype.updateInfo = function(artist, track) {
      var newString,
        _this = this;
      newString = "" + artist + " - <em class='track'>" + track + "</em>";
      if (this.settings.itunes) {
        return $.ajax({
          url: 'http://api.wipmania.com/jsonp?callback=?',
          dataType: 'jsonp',
          success: function(data) {
            var countryCode, queryString, term;
            countryCode = data.address.country_code;
            term = encodeURIComponent(artist + " " + track);
            queryString = "http://itunes.apple.com/search?entity=song&country=" + countryCode + "&term=" + term + "&limit=5&callback=?";
            return $.getJSON(queryString, function(data) {
              var link, result;
              if ((function() {
                var _i, _len, _ref, _results;
                _ref = data.results;
                _results = [];
                for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                  result = _ref[_i];
                  _results.push(track === result.trackName);
                }
                return _results;
              })()) {
                link = result.trackViewUrl;
              }
              if (link != null) {
                newString += " (<a href='" + link + "' class='itunes-link'>iTunes</a>)";
              }
              return _this.changeTooltip(newString);
            });
          }
        });
      } else {
        return this.changeTooltip(newString);
      }
    };

    Plugin.prototype.changeTooltip = function(msg) {
      return this.tooltip.fadeOut(function() {
        $(this).html(msg);
        return $(this).fadeIn();
      });
    };

    return Plugin;

  })();

  $.fn.juke = function(options) {
    return this.each(function() {
      return new Plugin(this, options).load();
    });
  };

}).call(this);
